name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync project to server
      run: rsync -avz --delete --exclude '.git' --exclude 'node_modules' ./ ubuntu@mansyur99.web.id:/var/www/html/mediainteraktif/

    - name: SSH to Server and deploy
      run: |
        ssh ubuntu@mansyur99.web.id << 'EOF'
        cd /var/www/html/mediainteraktif
        git pull origin main
        php artisan config:cache
        php artisan optimize
        sudo systemctl restart apache2
        EOF
